const {
  // addKitchen,
  // kitchens,
  // getSinglekitchen,
  // kitchen,
  // updateKitchen,
  // deleteKitchen,
  // addKitchenColors,
  // kitchenColor,
  // updateKitchenColor,
  // deleteKitchenColor,

  addAmbient,
  getAmbients,
  getAmbient,
  getSingleAmbient,
  updateAmbient,
  deleteAmbient,
  addAmbientColors,
  getAmbientColor,
  updateAmbientColor,
  deleteAmbientColor,

  // addBathroom,
  // Bathroom,
  // Bathrooms,
  // updateBathroom,
  // deleteBathroom,
  // addBathroomColors,
  // bathroomColor,
  // updatebathroomColor,
  // deletebathroomColor,
} = require('./visualizerControllers');

module.exports = {
  addAmbient,
  getAmbients,
  getAmbient,
  getSingleAmbient,
  updateAmbient,
  deleteAmbient,
  addAmbientColors,
  getAmbientColor,
  updateAmbientColor,
  deleteAmbientColor,
  // addBathroom,
  // Bathroom,
  // Bathrooms,
  // updateBathroom,
  // deleteBathroom,
  // addBathroomColors,
  // bathroomColor,
  // updatebathroomColor,
  // deletebathroomColor,
};
