const {
  addKitchen,
  kitchens,
  getSinglekitchen,
  kitchen,
  updateKitchen,
  deleteKitchen,
  addKitchenColors,
  kitchenColor,
  updateKitchenColor,
  deleteKitchenColor,
  addBathroom,
  Bathroom,
  Bathrooms,
  updateBathroom,
  deleteBathroom,
  addBathroomColors,
  bathroomColor,
  updatebathroomColor,
  deletebathroomColor,
} = require('./visualizerControllers');

module.exports = {
  addKitchen,
  kitchen,
  kitchens,
  getSinglekitchen,
  updateKitchen,
  deleteKitchen,
  addKitchenColors,
  kitchenColor,
  updateKitchenColor,
  deleteKitchenColor,
  addBathroom,
  Bathroom,
  Bathrooms,
  updateBathroom,
  deleteBathroom,
  addBathroomColors,
  bathroomColor,
  updatebathroomColor,
  deletebathroomColor,
};
